topics:
- name    : joy
  topic   : /stickbug/drivebase/joy/cmd_vel
  timeout : 0.5
  priority: 10
- name    : autonomous_driving
  topic   : /stickbug/drivebase/autonomous_driving/cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255