controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - stickbug/arm2/slider
      - stickbug/arm2/shoulder
      - stickbug/arm2/elbow
      - stickbug/arm2/w1
      - stickbug/arm2/w2
      - stickbug/arm4/slider
      - stickbug/arm4/shoulder
      - stickbug/arm4/elbow
      - stickbug/arm4/w1
      - stickbug/arm4/w2
      - stickbug/arm6/slider
      - stickbug/arm6/shoulder
      - stickbug/arm6/elbow
      - stickbug/arm6/w1
      - stickbug/arm6/w2
      - stickbug/arm1/slider
      - stickbug/arm1/shoulder
      - stickbug/arm1/elbow
      - stickbug/arm1/w1
      - stickbug/arm1/w2
      - stickbug/arm3/slider
      - stickbug/arm3/shoulder
      - stickbug/arm3/elbow
      - stickbug/arm3/w1
      - stickbug/arm3/w2
      - stickbug/arm5/slider
      - stickbug/arm5/shoulder
      - stickbug/arm5/elbow
      - stickbug/arm5/w1
      - stickbug/arm5/w2
  - name: arm_velocity_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - stickbug/arm2/slider
      - stickbug/arm2/shoulder
      - stickbug/arm2/elbow
      - stickbug/arm2/w1
      - stickbug/arm2/w2
      - stickbug/arm4/slider
      - stickbug/arm4/shoulder
      - stickbug/arm4/elbow
      - stickbug/arm4/w1
      - stickbug/arm4/w2
      - stickbug/arm6/slider
      - stickbug/arm6/shoulder
      - stickbug/arm6/elbow
      - stickbug/arm6/w1
      - stickbug/arm6/w2
      - stickbug/arm1/slider
      - stickbug/arm1/shoulder
      - stickbug/arm1/elbow
      - stickbug/arm1/w1
      - stickbug/arm1/w2
      - stickbug/arm3/slider
      - stickbug/arm3/shoulder
      - stickbug/arm3/elbow
      - stickbug/arm3/w1
      - stickbug/arm3/w2
      - stickbug/arm5/slider
      - stickbug/arm5/shoulder
      - stickbug/arm5/elbow
      - stickbug/arm5/w1
      - stickbug/arm5/w2
  - name: arm_effort_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - stickbug/arm2/slider
      - stickbug/arm2/shoulder
      - stickbug/arm2/elbow
      - stickbug/arm2/w1
      - stickbug/arm2/w2
      - stickbug/arm4/slider
      - stickbug/arm4/shoulder
      - stickbug/arm4/elbow
      - stickbug/arm4/w1
      - stickbug/arm4/w2
      - stickbug/arm6/slider
      - stickbug/arm6/shoulder
      - stickbug/arm6/elbow
      - stickbug/arm6/w1
      - stickbug/arm6/w2
      - stickbug/arm1/slider
      - stickbug/arm1/shoulder
      - stickbug/arm1/elbow
      - stickbug/arm1/w1
      - stickbug/arm1/w2
      - stickbug/arm3/slider
      - stickbug/arm3/shoulder
      - stickbug/arm3/elbow
      - stickbug/arm3/w1
      - stickbug/arm3/w2
      - stickbug/arm5/slider
      - stickbug/arm5/shoulder
      - stickbug/arm5/elbow
      - stickbug/arm5/w1
      - stickbug/arm5/w2