home_position:
- 0.3
- -0.25
- 0.3
- 0.0
- 0.0
- 0.7071
- 0.7071
is_poll_end: true
is_right_arm: true
stepper_position: 25000
u2d2: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT62AOBM-if00-port0
