arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - slider
    - shoulder
    - elbow
    - w1
    - w2
    - e1
    - e2
    - e3
  gains:
    slider:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_velocity_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - slider
    - shoulder
    - elbow
    - w1
    - w2
    - e1
    - e2
    - e3
  gains:
    slider:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - slider
    - shoulder
    - elbow
    - w1
    - w2
    - e1
    - e2
    - e3
  gains:
    slider:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    w2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    e3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
